# Generated by Django 3.1.3 on 2020-11-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-pub_date', '-pk'), 'verbose_name': '기사목록', 'verbose_name_plural': '기사목록'},
        ),
        migrations.AlterModelOptions(
            name='reporter',
            options={'verbose_name': '작성자목록', 'verbose_name_plural': '작성자목록'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(verbose_name='작성일시'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.reporter', verbose_name='작성자명'),
        ),
    ]
