# Generated by Django 3.1.3 on 2020-11-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '선택목록', 'verbose_name_plural': '선택목록'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '질문목록', 'verbose_name_plural': '질문목록'},
        ),
        migrations.AlterModelTable(
            name='choice',
            table='TB_QUESTION_CHOICE',
        ),
        migrations.AlterModelTable(
            name='question',
            table='TB_QUESTION',
        ),
    ]
